version: "3.8"
services:
  challenge-with-me-redis:
    container_name: challenge-with-me-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: challenge-with-me-redis
    ports:
      - "6379:6379"
    volumes:
      - ~/data/redis:/data
    command: redis-server --appendonly yes
  challenge-with-me-database:
    container_name: challenge-with-me-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: challenge-with-me-database
    environment:
      - MYSQL_DATABASE=challenge
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ~/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  challenge-with-me-app:
    container_name: challenge-with-me-app
    build: .
    depends_on:
      - challenge-with-me-database
      - challenge-with-me-redis
    image: challenge-with-me-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_SECRET=${OPENAI_SECRET}
    ports:
      - "80:8080"
    restart: always
