spring:
  social:
    google:
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_SECRET}
      redirect: http://localhost:8080/api/oauth/login/google
      url:
        login: https://accounts.google.com/o/oauth2/v2/auth
        token: https://oauth2.googleapis.com/token
        profile: https://www.googleapis.com/oauth2/v3/userinfo
  jwt:
    secretKey: ${JWT_SECRET}

openai:
  secretKey: ${OPENAI_SECRET}
  model: gpt-3.5-turbo-0125
